version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: apps/nestjs-mydoor/Dockerfile
    env_file:
      - apps/nestjs-mydoor/.env
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: apps/angular-mydoor/Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./apps/angular-mydoor/docker/certs:/etc/nginx/certs:ro
    restart: unless-stopped
